from enum import *

class UserRole(Enum):
    REGULAR_CLIENT = "REGULAR CLIENT"
    PREMIUM_CLIENT = "PREMIUM CLIENT"
    FINANCIAL_PLANNER = "FINANCIAL PLANNER"
    FINANCIAL_ADVISOR = "FINANCIAL ADVISOR"
    INVESTMENT_ANALYST = "INVESTMENT ANALYST"
    TECH_SUPPORT = "TECHNICAL SUPPORT"
    TELLER = "TELLER"
    COMPLIANCE_OFFICER = "COMPLIANCE OFFICER"

class AccessControl(Enum):
    VIEW = "VIEW"
    MODIFY = "MODIFY"
    EXECUTE = "EXECUTE"

class FinancialInstrument(Enum):
    BALANCE = "BALANCE"
    CLIENT_INFO = "CLIENT INFORMATION"
    INVESTMENT_PORTFOLIO = "INVESTMENT PORTFOLIO"
    CONTACT_DETAILS = "CONTACT DETAILS"
    MONEY_MARKET_INSTRUMENTS = "MONEY MARKET INSTRUMENTS"
    PRIV_CONSUMER_INSTRUMENTS = "PRIVATE CONSUMER INSTRUMENTS"
    DERIVATIVES_TRADING = "DERIVATIVES TRADING"
    INTEREST_INSTRUMENTS = "INTEREST INSTRUMENTS"
    CLIENT_ACCOUNT = "CLIENT ACCOUNT"